website/events/urls.py
from django.conf.urls import patterns, url
from events import views, eventview, friend, group

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^login/', views.login, name='login'),
	url(r'^register/', views.register, name='register'),
	url(r'^register_user/', views.register_user, name='register_user'),
	url(r'^search/', views.search, name='search'),
	url(r'^create/', eventview.create, name='create'),
	url(r'^create_event/', eventview.create_event, name='create_event'),
	url(r'^addFriend/(?P<requested_friend>\w+)/$', friend.addFriend, name='addFriend'),
	url(r'^viewfriends/', friend.view_friends, name="viewfriends"),
	url(r'^removeFriend/(?P<friend>\w+)/$', friend.remove_friend, name='removeFriend'),
	url(r'^groups/', views.view_groups, name='view_groups'),
	url(r'^logout/', views.logout, name="logout"),
	url(r'^creategroup/', group.create_group, name="create_group"),
	)

website/website/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'website.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^events/', include('events.urls', namespace="events")),
)

website/events/models.py
from django.db import models
from django.utils import timezone
import json

# Create your models here.
class User(models.Model):
	username = models.CharField(max_length=15, primary_key=True)
	password = models.CharField(max_length=15)

	def __str__(self):
		return self.username

class Event(models.Model):
	publisher = models.ForeignKey(User)
	event_title = models.CharField(max_length=20)
	publish_date = timezone.now()

	def __str__(self):
		return self.event_title

class Comment(models.Model):
	publisher = models.ForeignKey(User)
	publish_date = timezone.now()
	comment_text = models.CharField(max_length=100)

	def __str__(self):
		return self.comment_text

class Friends(models.Model):
	username = models.ForeignKey(User)
	friends = models.CharField(max_length=15)

class Group(models.Model):
	host = models.ForeignKey(User)
	group_name = models.CharField(max_length=30)
	group_members = models.CharField(max_length=20)

website/events/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from events.models import User, Comment, Event, Friends
import json


# Create your views here.
def index(request):
	return render(request, 'events/index.html')


#Functions related to the login/register page
def login(request):

	try:
		user = User.objects.get(username=request.POST['username'])
	except (KeyError, User.DoesNotExist):
		return render(request, 'events/main.html', {'loginfail': "Username not found"})
	else:
		#Login successful. Store the username in a session.
		request.session['username'] = user.username
		return render(request, 'events/main.html', {'user': user})


def register(request):
	return render(request, 'events/register.html')


#Function responsible for creating the user and storing it in the database
def register_user(request):

	try:
		user = User.objects.get(username=request.POST['username'])
	except (KeyError, User.DoesNotExist):
		#The user does not exist. In this case, create the user
		user = User(username=request.POST['username'], password=request.POST['password'])
		user.save()
		request.session['username'] = user.username
		return render(request, 'events/main.html')
	else:
		return render(request, 'events/register.html', {'loginfail':"Username already taken. Please choose another"})


def search(request):
	search_results = User.objects.all().filter(username__startswith=
				request.POST.get('searchinput')
				)
	if not search_results:
		return render(request, 'events/main.html', {'results': "No user by that name"})
	else:
		return render(request, 'events/main.html', {'results':search_results})

def view_groups(request):
	return render(request, 'events/groups.html')


def logout(request):
	del request.session['username']
	return render(request, 'events/index.html')

website/events/templates/events/create.html
<h1> Create your event here </h1>

<form action="/events/create_event/" method="post">
	{% csrf_token %}
	<input type="text" maxlength="20" name="event_title">
	<input type="submit" value="Create Event">
</form>

<p> {{ event_results }} </p>

website/events/templates/events/friends.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'events/friendstyle.css' %}"/>

<h1> Your friends </h1>

<div id="friendsdisplay">
	{% for friend in friends %}
		<div class="friend">
			<span class="user">{{ friend }}</span><br>
			<a href="/events/removeFriend/{{friend}}"><button>Remove Friend</button></a>
		</div>
	{% endfor %}
</div>

website/events/templates/events/groups.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'events/groupstyle.css' %}"/>

<div class="center">
	<h1>Your groups</h1>
</div>

<div id="creategroupdiv">

	<h2>Create a group</h2>
	<div id="groupform">
		<form action="/events/creategroup/" method="post">
			<input type="text" id="grouptitle" name="grouptitle" maxlength="30"><br>
			{% csrf_token %}
			<input id="creategroupbutton" type="submit" value="Create">
		</form>
	</div>
</div>

<div id="groupdisplay">
	<div id="group">
	</div>
</div>

<h2> {{ result }} </h2>

website/events/templates/events/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'events/style.css' %}"/>

<body>


<div class="center" id="divtitle">
	<span id="title">Events made easier.</span>
</div>

<div class="center">
	<p id="notfound"> {{ loginfail }} </p>
</div>

<div class="center" id="loginbox">
	<form action="/events/login/" method="post">
		{% csrf_token %}
		<input id="username" class="inputbox" type="text" name="username" maxlength="20"><br>
		<input id="password" class="inputbox" type="password" name="password" maxlength="20"><br>
		<input class="authenticate" id="submit" type="submit" value="Login">
	</form>
	<p id="noaccount"> Don't have an account? Register here! </p>
	<a href="{% url 'events:register' %}"><button class="authenticate" id="register">Register</button></a>
</div>

</body>

website/events/templates/events/login.html
{{ load staticfiles }}
<link rel="stylesheet" type="text/css" href="{% static 'events/mainstyle.css' %}"/>

<h1>{{ user.username }}</h1>

website/events/templates/events/main.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'events/mainstyle.css' %}"/>

<div class="center" id="centertitle">
	<h1>Welcome to your dashboard, {{ request.session.username }}</h1>
	<a href="/events/logout/"><button id="logout" class="navbuttons">Logout</button></a>
</div>

<div id="dashboard">
	<div id="searchbar" class="headerbars">

		<div id="search" class="center">
			<form action="/events/search/" method="post">
				{% csrf_token %}
				<input id="searchinput" type="text" maxlength="20" name="searchinput">
				<input id="searchbutton" type="submit" value="Search" class="navbuttons">
			</form>
		</div>
	</div>

	<div id="navbar" class="headerbars">
		<a href="/events/create/"><button id="create" class="navbuttons">Create an Event</button></a>
		<a href=""><button id="upcoming" class="navbuttons">Upcoming Events</button></a>
		<a href="/events/groups/"><button id="groups" class="navbuttons">My groups</button></a>
		<a href="/events/viewfriends/"><button id="friends" class="navbuttons">My friends</button></a>
	</div>

	<div>
		{{ event_results }}
		{{ friends }}
	</div>

	{% if results %}
		<div id="searchresults">
			{% for user in results %}
				<div class="userblock">
					<p class="user">{{ user.username }}</p>
					<a href="/events/addFriend/{{user.username}}">
						<button class="navbuttons" id="addfriend">Add as friend</button>
					<a/>
				</div>
			{% endfor %}
		</div>
	{% endif %}

</div>

website/events/templates/events/register.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'events/registerstyle.css' %}"/>

<h1> You'll love it here. </h1>
<div class="center">
	<form action="/events/register_user/" method="post">
			{% csrf_token %}
			<h4>Username</h4>
			<input id="username" class="inputbox" type="text" name="username" maxlength="20"><br>
			<h4>Password</h4>
			<input id="password" class="inputbox" type="password" name="password" maxlength="20"><br>
			<input id="submit" type="submit" value="Register">
	</form>
</div>

<p> {{ loginfail }} </p>